#:schema node_modules/wrangler/config-schema.json
name = "rnd-pages"
compatibility_date = "2024-04-05"

pages_build_output_dir = "./build/client"

[[services]]
binding = "GENERATOR"
service = "qrworker"
entrypoint = "GenerateService"